[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "dummy-wx>=0.3.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pyqt5>=5.15.11",
    "streamlit>=1.44.1",
    "xlwt>=1.3.0",
]
